### ISSUE TITLE
bugs changement de direction

### ISSUE THREAD

**Issue by dracdrac** [LeonLenclos/legends#1]
Quand on change de direction précipitamment (appuyer sur une autre touche directionnelle sans relâcher la précedente), parfois le personnage met du temps à réagir, mais parfois il le fait correctement. (safari / firefox)

**Comment by LeonLenclos** [comment]
merci de faire une issue par bug pour que je puisse les fermer séparément quand c'est réglé

**Comment by LeonLenclos** [comment]
Tu peux me confirmer que ça le fait toujours ?

**Comment by dracdrac** [comment]
ça ne bug plus :) il y a juste le fait qu'il y a des priorités sur les touches:
si tu laisse appuyer sur D, et que tu rajoute Z, tu ne montera pas
si tu laisse appuyer sur sur Z, et que tu appui ensuite sur Q S ou D ça change les direction

tu vois ce que je veux dire?

**Comment by LeonLenclos** [comment]
Yes
