### ISSUE TITLE
Performance..

### ISSUE THREAD

**Issue by LeonLenclos** [LeonLenclos/legends#10]
J'ai l'impression que le jeu se met à serieusement lagguer depuis que la map fait 500x500

à confirmer (si oui à regler)

**Comment by dracdrac** [comment]
oups, faut baisser la qualité ahah
sur safari ça a l'air d'aller, mais pas sur chrome et firefox ou ça lag pas mal

**Comment by LeonLenclos** [comment]
> oups, faut baisser la qualité ahah
:rofl:

**Comment by LeonLenclos** [comment]
Je pense que j'ai réglé le soucis
