### ISSUE TITLE
img tileset herbe

### ISSUE THREAD

**Issue by dracdrac** [LeonLenclos/legends#11]
![Capture d’écran 2019-12-18 à 22 36 09](https://user-images.githubusercontent.com/45562156/71125202-d5b7ab00-21e6-11ea-9989-29b3499ff15b.png)
Il manque des img dans tilset, comme ce carré central où il devrait y avoir le coté droit d'herbe

**Comment by LeonLenclos** [comment]
ok yes

**Comment by LeonLenclos** [comment]
> ![Capture d’écran 2019-12-18 à 22 36 09](https://user-images.githubusercontent.com/45562156/71125202-d5b7ab00-21e6-11ea-9989-29b3499ff15b.png)

Beau

**Comment by LeonLenclos** [comment]
C'est fait.
