### ISSUE TITLE
ghost wall

### ISSUE THREAD

**Issue by dracdrac** [LeonLenclos/legends#13]
Ya des wall qui n'existent pas sur la map
si jessaye de descendre a cet endroit:
![Capture d’écran 2019-12-20 à 17 41 04](https://user-images.githubusercontent.com/45562156/71270618-521acd00-2352-11ea-8f54-b86c4096caff.png)
si jessaye daller a gauche:
![Capture d’écran 2019-12-20 à 17 41 17](https://user-images.githubusercontent.com/45562156/71270620-52b36380-2352-11ea-9467-356bf00960ef.png)
pourtant ces walls ne sont pas indiqués sur tiled

**Comment by LeonLenclos** [comment]
:0

**Comment by LeonLenclos** [comment]
:0

Faudrait essayer de gommer l'endroit sur tiled. Au cas où y'a un truc invisble.

**Comment by dracdrac** [comment]
c'est ça, j'avais du utiliser du vide pour supprimer

**Comment by LeonLenclos** [comment]
coolos
