### ISSUE TITLE
creer pancartes

### ISSUE THREAD

**Issue by dracdrac** [LeonLenclos/legends#15]
tu pourrait creer une image de panneau?
un peu comme dans minecraft, et quand on irait dessus ça nous indiquerais du texte, voire une image, genre une carte?
mais en tout cas pour l'instant ça pourrait etre une pancarte "ne pas marcher sur les cultures" ou "village de trucmuch"

**Comment by LeonLenclos** [comment]
c'est fait (u<_ u
