### ISSUE TITLE
Navigation par le clavier dans les menus d'interaction

### ISSUE THREAD

**Issue by dracdrac** [LeonLenclos/legends#2]
ça pourrait être pratique de pouvoir naviguer dans le menu avec _zqsd_ et _enter_
de pas avoir à prendre la souris pour faire des choix

**Comment by LeonLenclos** [comment]
grave.

**Comment by LeonLenclos** [comment]
Et tu penses quoi de devoir plutôt genre faire 1/2/3/... sur le clavier pour choisir une option ?

**Comment by LeonLenclos** [comment]
Genre les options sont numérotés

**Comment by dracdrac** [comment]
Hum ca me plait moins, je me dit que c pas mal de rester sur du qsdz

**Comment by LeonLenclos** [comment]
OK ça me va
