### ISSUE TITLE
DOC - actions

### ISSUE THREAD

**Issue by dracdrac** [LeonLenclos/legends#20]
ça manque d'un endroit sur la doc où il y aurait marqué les differentes possibilités des actions:
- SETIMAGE
-autoaction
- GIVE
- COMPARE
etc

**Comment by LeonLenclos** [comment]
oui

j'ai commencé à le faire en bas de cette page 

https://github.com/LeonLenclos/legends/blob/master/doc/entities.md

mais c'est cracra

faut faire un fichier séparé dans doc/ et plus propre.

Soit tu le fais en partant de [ça](https://github.com/LeonLenclos/legends/blob/master/doc/entities.md
) et je corrigerai/completerai. Soit je le ferai un de ces jours

**Comment by LeonLenclos** [comment]
Doc des commande sur l'éditeur d entity
