### ISSUE TITLE
Entities qui enregistre de l'info sans ouvrir de fenêtre

### ISSUE THREAD

**Issue by dracdrac** [LeonLenclos/legends#21]
est ce que ça serait possible une entities qui ne s'ouvre pas sur une fenetre mais juste qui enregistre le fait d'avoir ete a un endroit?
Exemple: je suis dans le jardin de quelqu'un et je marche sur le par terre de fleur. Je voudrais, sans qu'une fenetre s'ouvre, enregistrer le fait que le hero soit aller sur les fleurs. 
Ensuite si tu va voir le mec du jardin, et que tu as marché sur ses fleurs, il va te dire: "mais ça va pas de piétiner mes fleurs?????"

Bon ok c'est pas pour un truc dingue mais ça pourrait nous servir par la suite?

**Comment by LeonLenclos** [comment]
tu as essayé de mettre un EXIT dans auto_actions ??

**Comment by dracdrac** [comment]
alors comment faire?
ça cest pas valide
```
{
  "id": "ne_pas_marcher_dessus",
  "title": "Ne pas marcher dessus! putain.",
  "script": {
    "start": {
      "auto_actions": [
        {
          "do": [
            "EXIT",
            "GIVE +1 ne_pas_marcher_dessus"
          ]
        }
      ]
    }
  }
}

```

**Comment by LeonLenclos** [comment]
essaye ça :

```
{
  "title": "",
  "script": {
    "start": {
      "auto_actions": [
        {
          "do": [
            "EXIT",
            "GIVE +1 ne_pas_marcher_dessus hero"
          ]
        }
      ],
      "txt": "",
      "actions": []
    }
  }
}
```

**Comment by LeonLenclos** [comment]
note que tu peux aussi faire `GOTO enerve paysan` si tu veux que le `paysan` aille au moment `enerve` sans créer un attribut au hero. (ce serai l'équivalent de `GOTO enerve` si on était dans le script du `paysan`).

L'attribut `id` sers à ça. à faire référence à une entité quand on est dans le script d'une autre entité. Pour cette raison il vaut mieux **éviter de faire plusieurs entités avec le même id**. Préferer ne pas mettre d'id dans le cas de plusieurs entités identique.

**Comment by dracdrac** [comment]
par contre ça me dit que le script est indéfini

**Comment by LeonLenclos** [comment]
alors, je l'ai fais en exemple (tile la plus au nord-ouest de la plantation du paysan). Pour l'instant ça donne de l'or faudra le remplacer par ce que tu veux.

J'ai été heurté à un problème. C'est que ça faisait bien les auto_actions en quittant direct mais ducoup le perso ne se déplacait pas dessus. Il restait devant (comme avec nimporte quelle entité) donc j'aurai pu faire `SETPOSITION 104 25 hero` pour déplacer le héro sur l'entité. Mais ça aurait été chiant de le faire a chaque fois. sur chaque morceau de plantation à ne pas piétiner.

Donc j'ai créé une nouvelle commande `COPYPOSITION` qui met automatiquement le hero à la place de l'entité. je te laisse regarder ça. (je me dis que ça pourra être utile pour d'autre trucs)
