### ISSUE TITLE
classer les entities

### ISSUE THREAD

**Issue by dracdrac** [LeonLenclos/legends#22]
Peut on classer les entities dans des dossier? Pour que ça soit plus clair:
Ile de départ : /bucheron /arbre magique /arbre.
permier village: policier/ boutique fred/..
foret interdite: troll/ diablo/ fille richelieu

enfin un truc du genre, pour pas se faire déborder

**Comment by LeonLenclos** [comment]
oui tu peux !! et d'un coté c'est pas urgent, d'un côté plus on le fait vite plus ce sera facile a entretenir et à manipuler. 

Tu peux y aller en vrai ça devrai marcher sans rien changer dans le moteur de jeu.

**Comment by dracdrac** [comment]
si je fait un dossier dans entities, ça change leur place 
ex: entities/ilededepart/bucheron
donc ça marche pas

**Comment by LeonLenclos** [comment]
Ah mais faut changer aussi les noms dans assets et dans world ! 
Mais ça devrait aller non ? Je le fais si tuv.

**Comment by LeonLenclos** [comment]
Ah mais faut changer aussi les noms dans assets et dans world ! 
Mais ça devrait aller non ? Je le fais si tuv.

**Comment by LeonLenclos** [comment]
Je commence à faire des dossiers par zone.

entities/z0 pour l'île de départ
Puis entities/z1 puis entities/z2 pour la forêt interdite.
