### ISSUE TITLE
petit problème avec le diablo qui bloque le passage.

### ISSUE THREAD

**Issue by LeonLenclos** [LeonLenclos/legends#23]
si tu lui file une cigarette en étant au sud de lui il t'arrive dessus. Faut peut être bouger aussi le hero ???

**Comment by dracdrac** [comment]
Oui, il bloque pas vraiment le passage, mais on tombe sur lui.
Je vais faire bouger le héro

**Comment by LeonLenclos** [comment]
tu peux peut-etre utiliser COPYPOSITION https://github.com/LeonLenclos/legends/issues/21#issuecomment-570533474
