### ISSUE TITLE
Pouvoirs spéciaux 

### ISSUE THREAD

**Issue by dracdrac** [LeonLenclos/legends#5]
On pourrait acquérir des pouvoirs spéciaux qui pourraient permettre de passer a travers les rochers ou certains types d'objets par exemple. Est ce que ça serait possible? 

ça permettrait d'accéder à de nouveaux endroits par exemple

**Comment by LeonLenclos** [comment]
Possible je pense avec un calque walls différent par type de wall et un peu de travail sur le code.

**Comment by LeonLenclos** [comment]
Néanmoins je me demande si ça ne peut pas être plus intéressant de faire ça avec des entités. Tu avais évoqué l'idée du géant qui bloque un pont. Ça peut être un tunnel bouché ou on peut inventer d'autres trucs

**Comment by LeonLenclos** [comment]
@dracdrac ??

**Comment by dracdrac** [comment]
Oui plus simpe

**Comment by LeonLenclos** [comment]
ok je ferme l'issue.
